### ISSUE TITLE
listview快速下拉并放手，会同时出发下拉刷新和cell上注册的onClick事件

### ISSUE THREAD

**Issue by EngsShi** [react-component/m-pull-to-refresh#11]
下拉滑动期间放手会触发cell的onClick事件，必须下拉停顿一下再放手才能避免触发onClick事件。

请问这个问题该如何避免

**Comment by warmhug** [comment]
gesture 好像没这个问题，怎么处理的？ @paranoidjk

**Comment by EngsShi** [comment]
补充： 没增加下拉刷新的listview，不会出现下拉动作触发onClick事件
