### ISSUE TITLE
Only activate Pull To Refresh when bottom of the PullToRefresh component is visible?

### ISSUE THREAD

**Issue by natterstefan** [react-component/m-pull-to-refresh#12]
Hi,

First of all, great work :) Maybe you can help me out with my problem. I have the following situation:

- I am using your component in react environment (web) which is loaded/displayed in a react-native webview
- the PullToRefresh component is wrapped around the entire page(-component)
- the react-native webview takes 100% of the device's screen
- the user should still be able to scroll up and down

_but_ the following happens now, when I add your component:

- when the user scrolls to the bottom of the page and up again, the PTL feature is activated and refresh the entire page

_what I need_

- it only refreshes when the user "sees" the bottom of your component
- or the page is at a certain scroll position (eg scrollTop = 0)

Something which helps me to let the user still scroll up, but only refresh at the top of the page.

Ideas
- can you solve it in your property (eg. add some new feature)
- or do I need to take care of it somehow (eg. find out scroll position in the webview (in the app?) and then enable/wrap the PTL or not?

Edit:
- I have already tried to wrap only the Head-Component (is always the one at the top of the rest), _but_ then you can pull this element down (above all the others). Which looks weird from the user experience perspective.

**Comment by warmhug** [comment]
What version are you using? The latest version should be able to meet your needs.

**Comment by natterstefan** [comment]
@warmhug I am using the latest version. After seeing this undocumented (not part of the README) property:

```
  getScrollContainer: () => document.body }
```

I was able to restrict the PTR element to the headline/header component. This enabled me to allow still scrolling up w/o triggering the PTR always.

> When you set direction="up", Only pull up to the bottom of the content, continue to pull up, will trigger PTR. Is this behavior unexpected?

I need it in the "down" case (eg. pull down the header).

**Comment by warmhug** [comment]
I will add `getScrollContainer` to README. But I still don't quite understand what you mean.
Welcome your pr.

**Comment by natterstefan** [comment]
@warmhug thanks for updating the README. This will hopefully help others. In the meanwhile I will close this issue as it is not relevant for me anymore and the example was most likely to abstract or specific for my case. Thank you for your time and help!
