### ISSUE TITLE
after theintergrate  component on the mobile,the touch scroll can not work.

### ISSUE THREAD

**Issue by peisheng** [react-component/m-pull-to-refresh#3]
Hello,after i intergrate this component, my page can not scroll by touch scroll on the mobile,is there any i miss?
mycode: 
      `<div id="main">
          <PullToRefresh
            loadingFunction={this.handlerLoading}
            loading={
              <div className="loading-center" style={{ marginTop: -3 }}>
                <Loading type="balls" color="#38acff" />
              </div>
            }>
            {this.props.children}
          </PullToRefresh>
        </div>`

**Comment by warmhug** [comment]
Use 1.0.0, it has big change.
